/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/685e570735fff2860290f57d.glb 
*/

import React, { useRef, useEffect } from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF, useFBX, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useControls } from 'leva'
import * as THREE from 'three'

export function Avatar(props) {

  const { animation } = props;
  const { headFollow, cursorFollow, wireframe } = useControls({
    headFollow: false,
    cursorFollow: false,
    wireframe: false
  });

  const group = useRef();
  const { scene } = useGLTF('models/685e570735fff2860290f57d.glb');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  const { animations: typingAnimation } = useFBX('animations/Typing.fbx');
  const { animations: fallingAnimation } = useFBX('animations/Falling.fbx');
  const { animations: fallingToRollgAnimation } = useFBX('animations/FallingToRoll.fbx');
  const { animations: standingAnimation } = useFBX('animations/Standing.fbx');

  typingAnimation[0].name = 'Typing';
  fallingAnimation[0].name = 'Falling';
  fallingToRollgAnimation[0].name = 'FallingToRoll';
  standingAnimation[0].name = 'Standing';


  const { actions } = useAnimations([
    typingAnimation[0],
    fallingAnimation[0],
    fallingToRollgAnimation[0],
    standingAnimation[0],
  ], clone);

  useFrame((state) => {
    if (headFollow) {
      const head = clone.getObjectByName("Head");
      if (head) head.lookAt(state.camera.position);
    }
    if (cursorFollow) {
      const target = new THREE.Vector3(state.pointer.x, state.pointer.y, 1);
      const spine = clone.getObjectByName("Spine2");
      if (spine) spine.lookAt(target);
    }
  });

  useEffect(() => {
    if (animation && actions && actions[animation]) {
      actions[animation].reset().fadeIn(0.5).play();
      return () => {
        if (actions[animation]) {
          actions[animation].reset().fadeOut(0.5).stop();
        }
      }
    }
  }, [animation, actions]);

  useEffect(() => {
    Object.values(materials).forEach((material) => {
      material.wireframe = wireframe;
    });
  }, [wireframe]);

  return (
    <group {...props} ref={group} dispose={null}>
      <primitive object={clone} />
    </group>
  )
}

useGLTF.preload('models/685e570735fff2860290f57d.glb')